"""add fields orders

Revision ID: 0396a961b346
Revises: fbcacf743aa9
Create Date: 2023-05-21 22:01:19.774219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0396a961b346'
down_revision = 'fbcacf743aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('order', sa.Column('model', sa.String(), nullable=True))
    op.add_column('order', sa.Column('year', sa.String(), nullable=True))
    op.create_index(op.f('ix_order_model'), 'order', ['model'], unique=False)
    op.create_index(op.f('ix_order_vin'), 'order', ['vin'], unique=False)
    op.create_index(op.f('ix_order_year'), 'order', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_year'), table_name='order')
    op.drop_index(op.f('ix_order_vin'), table_name='order')
    op.drop_index(op.f('ix_order_model'), table_name='order')
    op.drop_column('order', 'year')
    op.drop_column('order', 'model')
    op.drop_column('order', 'vin')
    # ### end Alembic commands ###
