"""add img in report

Revision ID: 085edf17caa5
Revises: 46b4b285a3eb
Create Date: 2023-05-15 14:40:31.480864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085edf17caa5'
down_revision = '46b4b285a3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'img')
    # ### end Alembic commands ###
