"""add reports

Revision ID: 09238d19a6c3
Revises: ea2a7863e4fa
Create Date: 2023-05-14 15:35:54.995321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09238d19a6c3'
down_revision = 'ea2a7863e4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created'), 'report', ['created'], unique=False)
    op.create_index(op.f('ix_report_description'), 'report', ['description'], unique=False)
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_index(op.f('ix_report_description'), table_name='report')
    op.drop_index(op.f('ix_report_created'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
