"""add report image

Revision ID: 5f900f0e45d5
Revises: 0396a961b346
Create Date: 2023-05-25 19:48:40.547630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f900f0e45d5'
down_revision = '0396a961b346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportimage_id'), 'reportimage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportimage_id'), table_name='reportimage')
    op.drop_table('reportimage')
    # ### end Alembic commands ###
