"""add vin in models

Revision ID: 925e3d41033b
Revises: 085edf17caa5
Create Date: 2023-05-20 10:41:59.222107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925e3d41033b'
down_revision = '085edf17caa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vin', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_vin'), 'user', ['vin'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vin'), table_name='user')
    op.drop_column('user', 'vin')
    # ### end Alembic commands ###
