"""comment

Revision ID: ea2a7863e4fa
Revises: 5e939a8460a3
Create Date: 2023-05-13 23:21:03.725492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2a7863e4fa'
down_revision = '5e939a8460a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
